
# tap repositories and their packages

tap homebrew/core
brew adns
brew allegro
brew asdf
brew autoconf
brew automake
brew awscli
brew cask
brew coreutils
brew csvkit
brew curl
brew direnv
brew dumb
brew emacs
brew exa
brew fish
brew flac
brew fontconfig
brew freetype
brew fzf
brew gdbm
brew gettext
brew git
brew glib
brew gmp
brew gnupg
brew gnutls
brew icu4c
brew ilmbase
brew imagemagick
brew jemalloc
brew jpeg
brew jq
brew libassuan
brew libde265
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libidn2
brew libksba
brew libogg
brew libomp
brew libpng
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvorbis
brew libvterm
brew libyaml
brew little-cms2
brew luajit
brew mas
brew msgpack
brew neofetch
brew neovim
brew nettle
brew node
brew npth
brew oniguruma
brew openexr
brew openjpeg
brew openssl
brew openssl@1.1
brew opus
brew opusfile
brew p11-kit
brew pcre
brew pcre2
brew physfs
brew pinentry
brew pipenv
brew pkg-config
brew pyenv
brew python
brew rbenv
brew readline
brew ruby
brew ruby-build
brew screenresolution
brew shared-mime-info
brew shellcheck
brew sqlite
brew telnet
brew terminal-notifier
brew tfenv
brew the_silver_searcher
brew theora
brew trash-cli
brew unbound
brew unibilium
brew unixodbc
brew webp
brew wget
brew x265
brew xz
brew yadm
brew yarn
brew zlib

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-fira-code

tap homebrew/services

tap homebrew/cask
cask dashlane
cask firefox
cask java
cask kitty
cask postico
cask slack
cask spotify
cask visual-studio-code

tap chrokh/tap
brew base16-manager

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask discord
cask gswitch
cask keybase
cask postgres
cask processing
cask spectacle
cask sqlpro-for-sqlite

# App Store applications
appstore 409201541 com.apple.iWork.Pages (8.1)
appstore 595191960 com.fiplab.clipboard (1.9.3)
