sudo: required
before_install:
    - sudo add-apt-repository -y ppa:fish-shell/release-2
    - sudo apt-get update
    - sudo apt-get -y install fish
    - curl -s "https://get.sdkman.io" | bash
    - bash test/prepare_tests.sh

install:
    - mkdir -p "${HOME}"/.config/fish/{completions,conf.d,functions}
    - cp completions/* "${HOME}"/.config/fish/completions/
    - cp conf.d/* "${HOME}"/.config/fish/conf.d/
    - cp functions/* "${HOME}"/.config/fish/functions/

jobs:
  include:
    - stage: Completion Tests
      script: ruby test/completion.rb
    - stage: General Wrapper Tests
      script: fish test/wrapper.fish
    - stage: Ticket-specific tests
      script:
        - bash -c "sdk install crash 1.3.0; sdk uninstall crash 1.3.0"; fish test/10_zombies_new.fish