#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  # look for a brewfile and bootstrap brew
  if [ -f "$HOME/.config/brewfile/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  # if we have fish make it the default shell
  if command -v fish >/dev/null 2>&1; then
    echo "Setting Fish as default shell"
    echo `which fish` | sudo tee -a /etc/shells
    chsh -s `which fish`
  fi
 
  # unified color theme hooks
  if command -v base16-manager >/dev/null 2>&1; then
    echo "Setting up system-wide colour theming"
    base16-manager install chriskempson/base16-shell
    base16-manager install chriskempson/base16-vim
    base16-manager install kdrag0n/base16-kitty
    base16-manager set rebecca
  fi

fi

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
